// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC3QLpdw84_x_Xl2o_o2GVZhuaPJWv1k4',
    appId: '1:571696707674:web:4f298beb32b955b007c063',
    messagingSenderId: '571696707674',
    projectId: 'spotify-demo-a7c69',
    authDomain: 'spotify-demo-a7c69.firebaseapp.com',
    storageBucket: 'spotify-demo-a7c69.appspot.com',
    measurementId: 'G-NRBDSW3YQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHYYIE_FyIiHVQ4vzdxfFnBWJG1MTHwUA',
    appId: '1:571696707674:android:e63b254757624ac907c063',
    messagingSenderId: '571696707674',
    projectId: 'spotify-demo-a7c69',
    storageBucket: 'spotify-demo-a7c69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBv49bqSiqdfB9iUNeefpW2j403f-yiI',
    appId: '1:571696707674:ios:5397705df208eb3f07c063',
    messagingSenderId: '571696707674',
    projectId: 'spotify-demo-a7c69',
    storageBucket: 'spotify-demo-a7c69.appspot.com',
    iosBundleId: 'com.spotify.spotifyDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiBv49bqSiqdfB9iUNeefpW2j403f-yiI',
    appId: '1:571696707674:ios:5397705df208eb3f07c063',
    messagingSenderId: '571696707674',
    projectId: 'spotify-demo-a7c69',
    storageBucket: 'spotify-demo-a7c69.appspot.com',
    iosBundleId: 'com.spotify.spotifyDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC3QLpdw84_x_Xl2o_o2GVZhuaPJWv1k4',
    appId: '1:571696707674:web:8fa02d7d4aab93e407c063',
    messagingSenderId: '571696707674',
    projectId: 'spotify-demo-a7c69',
    authDomain: 'spotify-demo-a7c69.firebaseapp.com',
    storageBucket: 'spotify-demo-a7c69.appspot.com',
    measurementId: 'G-BZ45FQNPEB',
  );
}
